[build]
  functions = "./netlify/functions"
  publish = "build"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[redirects]]
  from = "/api/*"
  to = "https://goonbackend-1.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/apiProxy/home"
  to = "/.netlify/functions/home"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200