[build]
  functions = "./netlify/functions"
  secrets_scan_omit_keys = ["REACT_APP_API_BASE_URL"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[redirects]]
  from = "/api/*"
  to = "https://goonbackend.onrender.com/:splat"
  status = 200
